name: Auto-bump packages
on:
  schedule:
    - cron: '37 2 * * *' # Run nightly at 02:37 UTC to avoid peak hour congestion
  workflow_dispatch: # Allow manual triggering

jobs:
  update-packages:
    runs-on: ubuntu-latest
    container: registry.opensuse.org/home/okurz/container/containers/obs-automation:latest
    steps:
      - name: Configure OBS Credentials
        run: |
          mkdir -p ~/.config/osc
          cat <<EOF > ~/.config/osc/oscrc
          [general]
          apiurl = https://api.opensuse.org
          [https://api.opensuse.org]
          user = ${{ secrets.OBS_USER }}
          pass = ${{ secrets.OBS_PASSWORD }}
          EOF

      - name: Checkout automation repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Run Auto-bump script
        env:
          OBS_USER: ${{ secrets.OBS_USER }}
        # Running directly via Python to process all maintained packages of the user
        run: python3 obs_automation/main.py --user ${{ secrets.OBS_USER }}
