name: Auto-bump cf-cli
on:
  schedule:
    - cron: '37 2 * * *' # Run nightly at 02:37 UTC to avoid peak hour congestion
  workflow_dispatch: # Allow manual triggering

jobs:
  update-package:
    runs-on: ubuntu-latest
    container: registry.opensuse.org/home/okurz/container/containers/obs-automation:latest
    steps:
      - name: Configure OBS Credentials
        run: |
          mkdir -p ~/.config/osc
          cat <<EOF > ~/.config/osc/oscrc
          [general]
          apiurl = https://api.opensuse.org
          [https://api.opensuse.org]
          user = ${{ secrets.OBS_USER }}
          pass = ${{ secrets.OBS_PASSWORD }}
          EOF

      - name: Checkout automation repository
        uses: actions/checkout@v4

      - name: Run Auto-bump script
        env:
          OBS_USER: ${{ secrets.OBS_USER }}
        # Running directly via Python since all dependencies are provided system-wide by zypper
        run: python3 obs_automation/main.py --project Cloud:Tools --package cf-cli --anitya-id 385503
